name: Setup
description: Setup mise and install dependencies

runs:
  using: 'composite'
  steps:
    - name: Setup mise
      uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0
      with:
        cache: true

    - name: Install dependencies
      run: pnpm ci
      shell: bash
