name: Setup
description: Setup mise and install dependencies

runs:
  using: 'composite'
  steps:
    - name: Setup mise
      uses: jdx/mise-action@5228313ee0372e111a38da051671ca30fc5a96db # v3
      with:
        cache: true

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
