name: Setup
description: Setup mise and install dependencies

runs:
  using: 'composite'
  steps:
    - name: Setup mise
      uses: jdx/mise-action@v2
      with:
        cache: true

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
