packages:
  - core
  - packages/*

ignoredBuiltDependencies:
  - '@prisma/engines'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - bufferutil
  - core-js
  - core-js-pure
  - esbuild
  - sharp
  - unrs-resolver

minimumReleaseAge: 4320
minimumReleaseAgeExclude: '@k8o/arte-odyssey'

onlyBuiltDependencies:
  - '@vercel/speed-insights'
  - lefthook
  - msw
