packages:
  - apps/*
  - packages/*

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/engines'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - bufferutil
  - core-js
  - core-js-pure
  - esbuild
  - sharp
  - unrs-resolver

minimumReleaseAge: 4320

minimumReleaseAgeExclude:
  - '@k8o/*'
  - next-devtools-mcp
  - '@storybook/addon-mcp'

onlyBuiltDependencies:
  - '@vercel/speed-insights'
  - lefthook
  - msw

overrides:
  valibot: '>=1.2.0'
  esbuild: '>=0.25.0'
