packages:
  - apps/*
  - packages/*

catalog:
  '@vitest/browser-playwright': 4.0.16
  '@vitest/coverage-istanbul': 4.0.16
  '@vitest/ui': 4.0.16
  vitest: 4.0.16
  vitest-browser-react: 2.0.2

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/engines'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - agent-browser
  - bufferutil
  - core-js
  - core-js-pure
  - esbuild
  - sharp
  - unrs-resolver

minimumReleaseAge: 4320

minimumReleaseAgeExclude:
  - '@k8o/*'

onlyBuiltDependencies:
  - '@vercel/speed-insights'
  - lefthook
  - msw
