packages:
  - apps/*
  - packages/*

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/engines'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - bufferutil
  - core-js
  - core-js-pure
  - esbuild
  - sharp
  - unrs-resolver

minimumReleaseAge: 4320

minimumReleaseAgeExclude:
  - '@k8o/*'
  - react
  - react-dom
  - next
  - '@next/*'

onlyBuiltDependencies:
  - '@vercel/speed-insights'
  - lefthook
  - msw
