packages:
  - apps/*
  - packages/*

catalog:
  '@vitest/browser-playwright': 4.0.18
  '@vitest/coverage-istanbul': 4.0.18
  '@vitest/ui': 4.0.18
  vitest: 4.0.18
  vitest-browser-react: 2.0.5

blockExoticSubdeps: true

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/engines'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - agent-browser
  - bufferutil
  - core-js
  - core-js-pure
  - edgedriver
  - esbuild
  - geckodriver
  - sharp
  - unrs-resolver

minimumReleaseAge: 4320

minimumReleaseAgeExclude:
  - '@k8o/*'

onlyBuiltDependencies:
  - lefthook
  - msw
