packages:
  - 'packages/*'
ignoredBuiltDependencies:
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - bufferutil
  - core-js-pure
  - esbuild
  - sharp
  - unrs-resolver
onlyBuiltDependencies:
  - '@vercel/speed-insights'
  - lefthook
  - msw
