packages:
  - apps/*
  - packages/*

catalog:
  '@vitest/browser-playwright': 4.0.15
  '@vitest/coverage-istanbul': 4.0.15
  '@vitest/ui': 4.0.15
  vitest: 4.0.15
  vitest-browser-react: 2.0.2

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/engines'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - bufferutil
  - core-js
  - core-js-pure
  - esbuild
  - sharp
  - unrs-resolver

minimumReleaseAge: 4320

minimumReleaseAgeExclude:
  - '@k8o/*'
  - next-devtools-mcp
  - '@storybook/addon-mcp'

onlyBuiltDependencies:
  - '@vercel/speed-insights'
  - lefthook
  - msw

overrides:
  esbuild: '>=0.25.0'
  valibot: '>=1.2.0'
