import { FC } from 'react';
import { ColorContrastUnit } from './color-contrast-unit';
import {
  SEMANTIC_COLOR_VARIANTS,
  getColorCode,
} from '@/app/design-system/_utils/color';

export const ColorContrastFg: FC<{
  colorCode: string;
  colorCodeDark: string;
}> = ({ colorCode, colorCodeDark }) => {
  return (
    <div className="flex flex-wrap items-center gap-x-2 gap-y-4">
      <ColorContrastUnit
        colorCode={colorCode}
        colorCodeDark={colorCodeDark}
        contrastName="base"
        contrastCode={getColorCode(
          SEMANTIC_COLOR_VARIANTS.base.bg.base.light,
        )}
        contrastCodeDark={getColorCode(
          SEMANTIC_COLOR_VARIANTS.base.bg.base.dark,
        )}
        variant="foreground"
      />
      <ColorContrastUnit
        colorCode={colorCode}
        colorCodeDark={colorCodeDark}
        contrastName="base-subtle"
        contrastCode={getColorCode(
          SEMANTIC_COLOR_VARIANTS.base.bg.subtle.light,
        )}
        contrastCodeDark={getColorCode(
          SEMANTIC_COLOR_VARIANTS.base.bg.subtle.dark,
        )}
        variant="foreground"
      />
      <ColorContrastUnit
        colorCode={colorCode}
        colorCodeDark={colorCodeDark}
        contrastName="base-mute"
        contrastCode={getColorCode(
          SEMANTIC_COLOR_VARIANTS.base.bg.mute.light,
        )}
        contrastCodeDark={getColorCode(
          SEMANTIC_COLOR_VARIANTS.base.bg.mute.dark,
        )}
        variant="foreground"
      />
      <ColorContrastUnit
        colorCode={colorCode}
        colorCodeDark={colorCodeDark}
        contrastName="base-emphasize"
        contrastCode={getColorCode(
          SEMANTIC_COLOR_VARIANTS.base.bg.emphasize.light,
        )}
        contrastCodeDark={getColorCode(
          SEMANTIC_COLOR_VARIANTS.base.bg.emphasize.dark,
        )}
        variant="foreground"
      />
      <ColorContrastUnit
        colorCode={colorCode}
        colorCodeDark={colorCodeDark}
        contrastName="base-inverse"
        contrastCode={getColorCode(
          SEMANTIC_COLOR_VARIANTS.base.bg.inverse.light,
        )}
        contrastCodeDark={getColorCode(
          SEMANTIC_COLOR_VARIANTS.base.bg.inverse.dark,
        )}
        variant="foreground"
      />
      <ColorContrastUnit
        colorCode={colorCode}
        colorCodeDark={colorCodeDark}
        contrastName="primary"
        contrastCode={getColorCode(
          SEMANTIC_COLOR_VARIANTS.primitive.primary.bg.light,
        )}
        contrastCodeDark={getColorCode(
          SEMANTIC_COLOR_VARIANTS.primitive.primary.bg.dark,
        )}
        variant="foreground"
      />
      <ColorContrastUnit
        colorCode={colorCode}
        colorCodeDark={colorCodeDark}
        contrastName="primary-subtle"
        contrastCode={getColorCode(
          SEMANTIC_COLOR_VARIANTS.primitive.primary.bgSubtle.light,
        )}
        contrastCodeDark={getColorCode(
          SEMANTIC_COLOR_VARIANTS.primitive.primary.bgSubtle.dark,
        )}
        variant="foreground"
      />
      <ColorContrastUnit
        colorCode={colorCode}
        colorCodeDark={colorCodeDark}
        contrastName="primary-mute"
        contrastCode={getColorCode(
          SEMANTIC_COLOR_VARIANTS.primitive.primary.bgMute.light,
        )}
        contrastCodeDark={getColorCode(
          SEMANTIC_COLOR_VARIANTS.primitive.primary.bgMute.dark,
        )}
        variant="foreground"
      />
      <ColorContrastUnit
        colorCode={colorCode}
        colorCodeDark={colorCodeDark}
        contrastName="primary-emphasize"
        contrastCode={getColorCode(
          SEMANTIC_COLOR_VARIANTS.primitive.primary.bgEmphasize.light,
        )}
        contrastCodeDark={getColorCode(
          SEMANTIC_COLOR_VARIANTS.primitive.primary.bgEmphasize.dark,
        )}
        variant="foreground"
      />
      <ColorContrastUnit
        colorCode={colorCode}
        colorCodeDark={colorCodeDark}
        contrastName="secondary"
        contrastCode={getColorCode(
          SEMANTIC_COLOR_VARIANTS.primitive.secondary.bg.light,
        )}
        contrastCodeDark={getColorCode(
          SEMANTIC_COLOR_VARIANTS.primitive.secondary.bg.dark,
        )}
        variant="foreground"
      />
      <ColorContrastUnit
        colorCode={colorCode}
        colorCodeDark={colorCodeDark}
        contrastName="secondary-subtle"
        contrastCode={getColorCode(
          SEMANTIC_COLOR_VARIANTS.primitive.secondary.bgSubtle.light,
        )}
        contrastCodeDark={getColorCode(
          SEMANTIC_COLOR_VARIANTS.primitive.secondary.bgSubtle.dark,
        )}
        variant="foreground"
      />
      <ColorContrastUnit
        colorCode={colorCode}
        colorCodeDark={colorCodeDark}
        contrastName="secondary-mute"
        contrastCode={getColorCode(
          SEMANTIC_COLOR_VARIANTS.primitive.secondary.bgMute.light,
        )}
        contrastCodeDark={getColorCode(
          SEMANTIC_COLOR_VARIANTS.primitive.secondary.bgMute.dark,
        )}
        variant="foreground"
      />
      <ColorContrastUnit
        colorCode={colorCode}
        colorCodeDark={colorCodeDark}
        contrastName="secondary-emphasize"
        contrastCode={getColorCode(
          SEMANTIC_COLOR_VARIANTS.primitive.secondary.bgEmphasize
            .light,
        )}
        contrastCodeDark={getColorCode(
          SEMANTIC_COLOR_VARIANTS.primitive.secondary.bgEmphasize
            .dark,
        )}
        variant="foreground"
      />
      <ColorContrastUnit
        colorCode={colorCode}
        colorCodeDark={colorCodeDark}
        contrastName="info"
        contrastCode={getColorCode(
          SEMANTIC_COLOR_VARIANTS.semantic.bg.info.light,
        )}
        contrastCodeDark={getColorCode(
          SEMANTIC_COLOR_VARIANTS.semantic.bg.info.dark,
        )}
        variant="foreground"
      />
      <ColorContrastUnit
        colorCode={colorCode}
        colorCodeDark={colorCodeDark}
        contrastName="success"
        contrastCode={getColorCode(
          SEMANTIC_COLOR_VARIANTS.semantic.bg.success.light,
        )}
        contrastCodeDark={getColorCode(
          SEMANTIC_COLOR_VARIANTS.semantic.bg.success.dark,
        )}
        variant="foreground"
      />
      <ColorContrastUnit
        colorCode={colorCode}
        colorCodeDark={colorCodeDark}
        contrastName="warning"
        contrastCode={getColorCode(
          SEMANTIC_COLOR_VARIANTS.semantic.bg.warning.light,
        )}
        contrastCodeDark={getColorCode(
          SEMANTIC_COLOR_VARIANTS.semantic.bg.warning.dark,
        )}
        variant="foreground"
      />
      <ColorContrastUnit
        colorCode={colorCode}
        colorCodeDark={colorCodeDark}
        contrastName="error"
        contrastCode={getColorCode(
          SEMANTIC_COLOR_VARIANTS.semantic.bg.error.light,
        )}
        contrastCodeDark={getColorCode(
          SEMANTIC_COLOR_VARIANTS.semantic.bg.error.dark,
        )}
        variant="foreground"
      />
    </div>
  );
};
