// チップ一覧を役割別に束ねるためのグループ定義（role-grouping.ts の groupByRole が参照）。
// 全115要素を重複なく1グループずつに割り当てる。
type BoardGroup = {
  label: string;
  tags: readonly string[];
};

export const BOARD_GROUPS: readonly BoardGroup[] = [
  { label: '文書ルート', tags: ['html'] },
  {
    label: '文書メタデータ',
    tags: ['base', 'head', 'link', 'meta', 'style', 'title'],
  },
  { label: '本文ルート', tags: ['body'] },
  {
    label: 'コンテンツ区分',
    tags: [
      'address',
      'article',
      'aside',
      'footer',
      'h1',
      'h2',
      'h3',
      'h4',
      'h5',
      'h6',
      'header',
      'hgroup',
      'main',
      'nav',
      'section',
      'search',
    ],
  },
  {
    label: 'テキストの塊',
    tags: [
      'blockquote',
      'dd',
      'div',
      'dl',
      'dt',
      'figcaption',
      'figure',
      'hr',
      'li',
      'menu',
      'ol',
      'p',
      'pre',
      'ul',
    ],
  },
  {
    label: 'インライン要素',
    tags: [
      'a',
      'abbr',
      'b',
      'bdi',
      'bdo',
      'br',
      'cite',
      'code',
      'data',
      'dfn',
      'em',
      'i',
      'kbd',
      'mark',
      'q',
      'rp',
      'rt',
      'ruby',
      's',
      'samp',
      'small',
      'span',
      'strong',
      'sub',
      'sup',
      'time',
      'u',
      'var',
      'wbr',
    ],
  },
  {
    label: '画像・メディア',
    tags: ['area', 'audio', 'img', 'map', 'track', 'video'],
  },
  {
    label: '埋め込み',
    tags: ['embed', 'iframe', 'object', 'picture', 'source'],
  },
  { label: 'SVG・MathML', tags: ['math', 'svg'] },
  { label: 'スクリプト', tags: ['canvas', 'noscript', 'script'] },
  { label: '編集の差分', tags: ['del', 'ins'] },
  {
    label: 'テーブル',
    tags: [
      'caption',
      'col',
      'colgroup',
      'table',
      'tbody',
      'td',
      'tfoot',
      'th',
      'thead',
      'tr',
    ],
  },
  {
    label: 'フォーム',
    tags: [
      'button',
      'datalist',
      'fieldset',
      'form',
      'input',
      'label',
      'legend',
      'meter',
      'optgroup',
      'option',
      'output',
      'progress',
      'select',
      'selectedcontent',
      'textarea',
    ],
  },
  { label: '対話要素', tags: ['details', 'dialog', 'summary'] },
  { label: 'Web Components', tags: ['slot', 'template'] },
];
