import type { HtmlElementInfo } from '../_types/html-element';

// HTML Living Standard の elements index を出典とする要素データ。
// 各要素の content categories / content model(子) / contexts(親) を構造化したもの。
// 生成補助のうえ手動補正済み。要素一覧は HTML_ELEMENT_TAGS を参照。
export const HTML_ELEMENTS: readonly HtmlElementInfo[] = [
  {
    tag: 'a',
    description: 'ハイパーリンクを表すアンカー要素',
    categories: ['flow', 'phrasing', 'palpable'],
    conditionalCategories: ['interactive'],
    contentModel: {
      kind: 'transparent',
      categories: [],
      elements: [],
      note: '親のcontent modelに従う。子孫にinteractiveコンテンツやa要素、tabindex属性を持つ要素を含めてはならない',
    },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'abbr',
    description: '略語・頭字語を表す要素',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'address',
    description: '連絡先情報を表す要素',
    categories: ['flow', 'palpable'],
    contentModel: {
      kind: 'elements',
      categories: ['flow'],
      elements: [],
      note: '見出し・sectioning・header/footer・address子孫は不可',
    },
    contexts: { categories: ['flow'], elements: [] },
    void: false,
  },
  {
    tag: 'area',
    description: 'イメージマップ上の領域を表す要素',
    categories: ['flow', 'phrasing'],
    contentModel: { kind: 'empty', categories: [], elements: [] },
    contexts: {
      categories: [],
      elements: [],
      conditionalElements: ['map'],
      note: 'map要素の子孫であること',
    },
    void: true,
  },
  {
    tag: 'article',
    description: '自己完結した独立コンテンツを表す要素',
    categories: ['flow', 'sectioning', 'palpable'],
    contentModel: { kind: 'elements', categories: ['flow'], elements: [] },
    contexts: { categories: ['flow'], elements: [] },
    void: false,
  },
  {
    tag: 'aside',
    description: '本筋から外れた補足コンテンツを表す要素',
    categories: ['flow', 'sectioning', 'palpable'],
    contentModel: { kind: 'elements', categories: ['flow'], elements: [] },
    contexts: { categories: ['flow'], elements: [] },
    void: false,
  },
  {
    tag: 'audio',
    description: '音声を埋め込み再生する要素',
    categories: ['flow', 'phrasing', 'embedded'],
    conditionalCategories: ['interactive', 'palpable'],
    contentModel: {
      kind: 'transparent',
      categories: [],
      elements: ['source', 'track'],
      note: '親のcontent modelに従う。src属性がなければsource、その後track、メディア要素を子孫に含めない',
    },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'b',
    description: '注目を引くテキストを表す要素',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'base',
    description: '文書の基準URL・既定ターゲットを指定する要素',
    categories: ['metadata'],
    contentModel: { kind: 'empty', categories: [], elements: [] },
    contexts: { categories: [], elements: ['head'] },
    void: true,
  },
  {
    tag: 'bdi',
    description: '双方向テキストを分離する要素',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'bdo',
    description: 'テキストの書字方向を明示的に上書きする要素',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'blockquote',
    description: '他から引用したブロックを表す要素',
    categories: ['flow', 'palpable'],
    contentModel: { kind: 'elements', categories: ['flow'], elements: [] },
    contexts: { categories: ['flow'], elements: [] },
    void: false,
  },
  {
    tag: 'body',
    description: '文書の本文コンテンツを表すルート直下の要素',
    categories: [],
    contentModel: { kind: 'elements', categories: ['flow'], elements: [] },
    contexts: {
      categories: [],
      elements: ['html'],
      note: 'html要素の2番目の子',
    },
    void: false,
  },
  {
    tag: 'br',
    description: '改行を表す要素',
    categories: ['flow', 'phrasing'],
    contentModel: { kind: 'empty', categories: [], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: true,
  },
  {
    tag: 'button',
    description: 'クリック可能なボタンを表す要素',
    categories: ['flow', 'phrasing', 'interactive', 'palpable'],
    formCategories: ['listed', 'labelable', 'submittable', 'form-associated'],
    contentModel: {
      kind: 'elements',
      categories: ['phrasing'],
      elements: [],
      note: 'インタラクティブ要素を子孫に持たない phrasing content',
    },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'canvas',
    description: 'スクリプトで描画する解像度依存ビットマップ領域',
    categories: ['flow', 'phrasing', 'embedded', 'palpable'],
    contentModel: {
      kind: 'transparent',
      categories: [],
      elements: [],
      note: '親のcontent modelに従う(透過)。インタラクティブ要素やフォーム要素を含む代替コンテンツを配置可能',
    },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'caption',
    description: 'テーブルのタイトルやキャプションを表す要素',
    categories: [],
    contentModel: {
      kind: 'elements',
      categories: ['flow'],
      elements: [],
      note: 'table を子孫に持たない flow content',
    },
    contexts: {
      categories: [],
      elements: ['table'],
      note: 'table要素の最初の子',
    },
    void: false,
  },
  {
    tag: 'cite',
    description: '作品の題名を表す要素',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'code',
    description: 'コンピュータコードの断片を表す要素',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'col',
    description: 'テーブルの列を表す要素',
    categories: [],
    contentModel: { kind: 'empty', categories: [], elements: [] },
    contexts: {
      categories: [],
      elements: ['colgroup'],
      note: 'span属性を持たないcolgroupの子',
    },
    void: true,
  },
  {
    tag: 'colgroup',
    description: 'テーブルの列グループを表す要素',
    categories: [],
    contentModel: {
      kind: 'elements',
      categories: [],
      elements: [],
      conditionalElements: ['col', 'template'],
      note: 'span属性を持たない場合、col要素とtemplate要素を子に持つ',
    },
    contexts: { categories: [], elements: ['table'] },
    void: false,
  },
  {
    tag: 'data',
    description: '内容に機械可読な値を関連付ける要素',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'datalist',
    description: '入力候補となるoption群を提供する要素',
    categories: ['flow', 'phrasing'],
    contentModel: {
      kind: 'elements',
      categories: ['phrasing'],
      elements: [],
      conditionalCategories: ['script-supporting'],
      conditionalElements: ['option'],
      note: 'phrasing content、またはoption要素とscript-supporting要素の組み合わせ',
    },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'dd',
    description: '記述リストの説明・値部分を表す要素',
    categories: [],
    contentModel: { kind: 'elements', categories: ['flow'], elements: [] },
    contexts: {
      categories: [],
      elements: ['dl', 'div'],
      note: 'dl要素内、またはdl内のdiv要素内',
    },
    void: false,
  },
  {
    tag: 'del',
    description: 'ドキュメントから削除された内容を表す。',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: {
      kind: 'transparent',
      categories: [],
      elements: [],
      note: '親のcontent modelに従う。',
    },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'details',
    description: '開閉して情報を表示する開示ウィジェット。',
    categories: ['flow', 'interactive', 'palpable'],
    contentModel: {
      kind: 'elements',
      categories: ['flow'],
      elements: ['summary'],
    },
    contexts: { categories: ['flow'], elements: [] },
    void: false,
  },
  {
    tag: 'dfn',
    description: '用語の定義箇所を表す。',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: {
      kind: 'elements',
      categories: ['phrasing'],
      elements: [],
    },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'dialog',
    description: 'ダイアログボックスやサブウィンドウ。',
    categories: ['flow'],
    contentModel: { kind: 'elements', categories: ['flow'], elements: [] },
    contexts: { categories: ['flow'], elements: [] },
    void: false,
  },
  {
    tag: 'div',
    description: '汎用のブロックレベルコンテナ。',
    categories: [
      'flow',
      'palpable',
      'select-inner',
      'optgroup-inner',
      'option-inner',
    ],
    contentModel: {
      kind: 'elements',
      categories: ['flow'],
      elements: [],
      conditionalCategories: ['select-inner', 'optgroup-inner', 'option-inner'],
    },
    contexts: {
      categories: ['flow', 'select-inner', 'optgroup-inner', 'option-inner'],
      elements: ['dl'],
    },
    void: false,
  },
  {
    tag: 'dl',
    description: '名前と値の組による説明リスト。',
    categories: ['flow'],
    conditionalCategories: ['palpable'],
    contentModel: {
      kind: 'elements',
      categories: ['script-supporting'],
      elements: ['dt', 'dd', 'div'],
    },
    contexts: { categories: ['flow'], elements: [] },
    void: false,
  },
  {
    tag: 'dt',
    description: '説明リストの項目名や用語。',
    categories: [],
    contentModel: {
      kind: 'elements',
      categories: ['flow'],
      elements: [],
    },
    contexts: {
      categories: [],
      elements: ['dl', 'div'],
    },
    void: false,
  },
  {
    tag: 'em',
    description: 'テキストの強調を表す。',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'embed',
    description: '外部アプリやプラグインの埋め込み点。',
    categories: ['flow', 'phrasing', 'embedded', 'interactive', 'palpable'],
    contentModel: { kind: 'empty', categories: [], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: true,
  },
  {
    tag: 'fieldset',
    description: 'フォーム部品をまとめるグループ。',
    categories: ['flow', 'palpable'],
    formCategories: ['listed', 'form-associated'],
    contentModel: {
      kind: 'elements',
      categories: ['flow'],
      elements: ['legend'],
    },
    contexts: { categories: ['flow'], elements: [] },
    void: false,
  },
  {
    tag: 'figcaption',
    description: 'figureのキャプションや説明。',
    categories: [],
    contentModel: { kind: 'elements', categories: ['flow'], elements: [] },
    contexts: { categories: [], elements: ['figure'] },
    void: false,
  },
  {
    tag: 'figure',
    description: 'キャプション付きの自己完結的な図表。',
    categories: ['flow', 'palpable'],
    contentModel: {
      kind: 'elements',
      categories: ['flow'],
      elements: ['figcaption'],
    },
    contexts: { categories: ['flow'], elements: [] },
    void: false,
  },
  {
    tag: 'footer',
    description: 'セクションのフッター。著者情報や関連リンクを示す。',
    categories: ['flow', 'palpable'],
    contentModel: {
      kind: 'elements',
      categories: ['flow'],
      elements: [],
      note: 'header/footer を子孫に含めることはできない',
    },
    contexts: { categories: ['flow'], elements: [] },
    void: false,
  },
  {
    tag: 'form',
    description: '送信可能なデータを表すフォーム。',
    categories: ['flow', 'palpable'],
    contentModel: {
      kind: 'elements',
      categories: ['flow'],
      elements: [],
      note: 'form 要素を子孫に含めることはできない',
    },
    contexts: { categories: ['flow'], elements: [] },
    void: false,
  },
  {
    tag: 'h1',
    description: '最上位の見出し。',
    categories: ['flow', 'heading', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['flow'], elements: ['legend', 'summary'] },
    void: false,
  },
  {
    tag: 'h2',
    description: '第2レベルの見出し。',
    categories: ['flow', 'heading', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['flow'], elements: ['legend', 'summary'] },
    void: false,
  },
  {
    tag: 'h3',
    description: '第3レベルの見出し。',
    categories: ['flow', 'heading', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['flow'], elements: ['legend', 'summary'] },
    void: false,
  },
  {
    tag: 'h4',
    description: '第4レベルの見出し。',
    categories: ['flow', 'heading', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['flow'], elements: ['legend', 'summary'] },
    void: false,
  },
  {
    tag: 'h5',
    description: '第5レベルの見出し。',
    categories: ['flow', 'heading', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['flow'], elements: ['legend', 'summary'] },
    void: false,
  },
  {
    tag: 'h6',
    description: '最下位レベルの見出し。',
    categories: ['flow', 'heading', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['flow'], elements: ['legend', 'summary'] },
    void: false,
  },
  {
    tag: 'head',
    description: '文書のメタデータを格納する要素。',
    categories: [],
    contentModel: {
      kind: 'elements',
      categories: ['metadata'],
      elements: [],
    },
    contexts: { categories: [], elements: ['html'] },
    void: false,
  },
  {
    tag: 'header',
    description: 'セクションの導入部やナビゲーションを示す。',
    categories: ['flow', 'palpable'],
    contentModel: {
      kind: 'elements',
      categories: ['flow'],
      elements: [],
      note: 'header/footer を子孫に含めることはできない',
    },
    contexts: { categories: ['flow'], elements: [] },
    void: false,
  },
  {
    tag: 'hgroup',
    description: '見出しと副題をまとめるグループ。',
    categories: ['flow', 'heading', 'palpable'],
    contentModel: {
      kind: 'elements',
      categories: ['script-supporting'],
      elements: ['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'p'],
    },
    contexts: { categories: ['flow'], elements: ['legend', 'summary'] },
    void: false,
  },
  {
    tag: 'hr',
    description: '段落レベルのテーマの区切り。',
    categories: ['flow', 'select-inner'],
    contentModel: { kind: 'empty', categories: [], elements: [] },
    contexts: { categories: ['flow', 'select-inner'], elements: [] },
    void: true,
  },
  {
    tag: 'html',
    description: 'HTML文書のルート要素。head と body を含む',
    categories: [],
    contentModel: {
      kind: 'elements',
      categories: [],
      elements: ['head', 'body'],
    },
    contexts: {
      categories: [],
      elements: [],
      special: 'root',
      note: 'ルート要素',
    },
    void: false,
  },
  {
    tag: 'i',
    description: '別の声調・気分など慣用的なテキスト範囲(斜体)',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'iframe',
    description: '入れ子のブラウジングコンテキスト(インラインフレーム)',
    categories: ['flow', 'phrasing', 'embedded', 'interactive', 'palpable'],
    contentModel: { kind: 'empty', categories: [], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: true,
  },
  {
    tag: 'img',
    description: '画像を埋め込む要素',
    categories: ['flow', 'phrasing', 'embedded', 'palpable'],
    conditionalCategories: ['interactive'],
    formCategories: ['form-associated'],
    contentModel: { kind: 'empty', categories: [], elements: [] },
    contexts: { categories: ['phrasing'], elements: ['picture'] },
    void: true,
  },
  {
    tag: 'input',
    description: 'フォームの各種入力コントロール',
    categories: ['flow', 'phrasing'],
    conditionalCategories: ['interactive', 'palpable'],
    formCategories: [
      'listed',
      'labelable',
      'submittable',
      'resettable',
      'form-associated',
    ],
    contentModel: { kind: 'empty', categories: [], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: true,
  },
  {
    tag: 'ins',
    description: '文書に追加された内容を表す要素',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: {
      kind: 'transparent',
      categories: [],
      elements: [],
      note: '親のcontent modelに従う',
    },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'kbd',
    description: 'ユーザー入力(キー入力等)を表す要素',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'label',
    description: 'フォームコントロールのキャプション(ラベル)',
    categories: ['flow', 'phrasing', 'interactive', 'palpable'],
    contentModel: {
      kind: 'elements',
      categories: ['phrasing'],
      elements: [],
    },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'legend',
    description: 'fieldset のキャプション(説明見出し)',
    categories: [],
    contentModel: {
      kind: 'elements',
      categories: ['phrasing', 'heading'],
      elements: [],
    },
    contexts: { categories: [], elements: ['fieldset', 'optgroup'] },
    void: false,
  },
  {
    tag: 'li',
    description: 'リストの項目',
    categories: [],
    contentModel: { kind: 'elements', categories: ['flow'], elements: [] },
    contexts: {
      categories: [],
      elements: ['ol', 'ul', 'menu'],
    },
    void: false,
  },
  {
    tag: 'link',
    description: '外部リソースへのリンク(メタデータ)',
    categories: ['metadata'],
    conditionalCategories: ['flow', 'phrasing'],
    conditionalNote:
      'itemprop 属性があるか rel が body-ok キーワード（stylesheet / preload / preconnect 等）のみのとき（body 内にも置ける）',
    contentModel: { kind: 'empty', categories: [], elements: [] },
    contexts: {
      categories: [],
      elements: ['head'],
      conditionalElements: ['noscript'],
    },
    void: true,
  },
  {
    tag: 'main',
    description: '文書の主要コンテンツを表す要素',
    categories: ['flow', 'palpable'],
    contentModel: { kind: 'elements', categories: ['flow'], elements: [] },
    contexts: { categories: ['flow'], elements: [] },
    void: false,
  },
  {
    tag: 'map',
    description: '画像のクリック可能領域(イメージマップ)を定義する要素',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: {
      kind: 'transparent',
      categories: [],
      elements: ['area'],
      note: '親のcontent modelに従う。子孫に area 要素を持てる',
    },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'mark',
    description: '参照や強調のためにハイライトされたテキスト',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'math',
    description: 'MathMLによる数式表現のルート要素',
    categories: ['flow', 'phrasing', 'embedded', 'palpable'],
    contentModel: {
      kind: 'foreign',
      categories: [],
      elements: [],
      note: 'MathMLの独自コンテンツ',
    },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'menu',
    description: '操作項目を並べたツールバー風のリスト',
    categories: ['flow'],
    conditionalCategories: ['palpable'],
    contentModel: {
      kind: 'elements',
      categories: ['script-supporting'],
      elements: ['li'],
    },
    contexts: { categories: ['flow'], elements: [] },
    void: false,
  },
  {
    tag: 'meta',
    description: '文書のメタデータを表す要素',
    categories: ['metadata'],
    conditionalCategories: ['flow', 'phrasing'],
    conditionalNote: 'itemprop 属性があるとき（microdata。body 内にも置ける）',
    contentModel: { kind: 'empty', categories: [], elements: [] },
    contexts: {
      categories: [],
      elements: ['head'],
      conditionalElements: ['noscript'],
      note: 'noscript内、または phrasing コンテキストにも置ける場合がある',
    },
    void: true,
  },
  {
    tag: 'meter',
    description: '既知の範囲内のスカラー値を表すゲージ',
    categories: ['flow', 'phrasing', 'palpable'],
    formCategories: ['labelable'],
    contentModel: {
      kind: 'elements',
      categories: ['phrasing'],
      elements: [],
      note: '子孫に meter を含まない phrasing コンテンツ',
    },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'nav',
    description: 'ナビゲーションリンクのセクション',
    categories: ['flow', 'sectioning', 'palpable'],
    contentModel: { kind: 'elements', categories: ['flow'], elements: [] },
    contexts: { categories: ['flow'], elements: [] },
    void: false,
  },
  {
    tag: 'noscript',
    description: 'スクリプト無効時に表示する代替コンテンツ',
    categories: [
      'metadata',
      'flow',
      'phrasing',
      'select-inner',
      'optgroup-inner',
    ],
    contentModel: {
      kind: 'varies',
      categories: [],
      elements: [],
      note: '文脈により異なる(noscriptはscript有効/無効で変化)',
    },
    contexts: {
      categories: [],
      elements: [],
      conditionalElements: ['head'],
      note: 'head 内、または phrasing コンテキストに置ける場合がある',
    },
    void: false,
  },
  {
    tag: 'object',
    description: '画像やネストした文書等の外部リソースを埋め込む要素',
    categories: ['flow', 'phrasing', 'embedded', 'palpable'],
    conditionalCategories: ['interactive'],
    formCategories: ['listed', 'form-associated'],
    contentModel: {
      kind: 'transparent',
      categories: [],
      elements: [],
      note: '親のcontent modelに従う',
    },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'ol',
    description: '順序付きリスト',
    categories: ['flow'],
    conditionalCategories: ['palpable'],
    contentModel: {
      kind: 'elements',
      categories: ['script-supporting'],
      elements: ['li'],
    },
    contexts: { categories: ['flow'], elements: [] },
    void: false,
  },
  {
    tag: 'optgroup',
    description: 'select内の選択肢をグループ化する要素',
    categories: ['select-inner'],
    contentModel: {
      kind: 'elements',
      categories: ['optgroup-inner'],
      elements: ['legend'],
    },
    contexts: {
      categories: [],
      elements: ['select'],
      conditionalElements: ['div'],
    },
    void: false,
  },
  {
    tag: 'option',
    description: 'select/datalist/optgroup内の選択肢を表す要素',
    categories: ['select-inner', 'optgroup-inner'],
    contentModel: {
      kind: 'text',
      categories: [],
      elements: [],
      note: 'テキスト、または option 要素の内側コンテンツ',
    },
    contexts: {
      categories: [],
      elements: ['select', 'datalist', 'optgroup'],
      conditionalElements: ['div'],
    },
    void: false,
  },
  {
    tag: 'output',
    description: '計算結果を表示する要素。',
    categories: ['flow', 'phrasing', 'palpable'],
    formCategories: ['listed', 'labelable', 'resettable', 'form-associated'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'p',
    description: '段落を表す要素。',
    categories: ['flow', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['flow'], elements: [] },
    void: false,
  },
  {
    tag: 'picture',
    description: '複数の画像候補から選択する画像コンテナ。',
    categories: ['flow', 'phrasing', 'embedded', 'palpable'],
    contentModel: {
      kind: 'elements',
      categories: ['script-supporting'],
      elements: ['source', 'img'],
    },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'pre',
    description: '整形済みテキストを表す要素。',
    categories: ['flow', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['flow'], elements: [] },
    void: false,
  },
  {
    tag: 'progress',
    description: 'タスクの進捗状況を示す要素。',
    categories: ['flow', 'phrasing', 'palpable'],
    formCategories: ['labelable'],
    contentModel: {
      kind: 'elements',
      categories: ['phrasing'],
      elements: [],
    },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'q',
    description: '短いインライン引用を表す要素。',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'rp',
    description: 'ルビ非対応時の括弧を示す要素。',
    categories: [],
    contentModel: { kind: 'text', categories: [], elements: [] },
    contexts: { categories: [], elements: ['ruby'] },
    void: false,
  },
  {
    tag: 'rt',
    description: 'ルビのふりがなテキストを表す要素。',
    categories: [],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: [], elements: ['ruby'] },
    void: false,
  },
  {
    tag: 'ruby',
    description: 'ルビ注釈を付ける要素。',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: {
      kind: 'elements',
      categories: ['phrasing'],
      elements: ['rt', 'rp'],
    },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 's',
    description: '正確でなくなった内容を示す取り消し線要素。',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'samp',
    description: 'プログラムの出力サンプルを示す要素。',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'script',
    description: 'スクリプトやデータを埋め込む要素。',
    categories: ['metadata', 'flow', 'phrasing', 'script-supporting'],
    contentModel: {
      kind: 'text',
      categories: [],
      elements: [],
      note: 'JavaScript等のスクリプト/データ',
    },
    contexts: {
      categories: ['phrasing', 'script-supporting'],
      elements: ['head'],
    },
    void: false,
  },
  {
    tag: 'search',
    description: '検索やフィルタリング操作のための領域を表す要素。',
    categories: ['flow', 'palpable'],
    contentModel: { kind: 'elements', categories: ['flow'], elements: [] },
    contexts: { categories: ['flow'], elements: [] },
    void: false,
  },
  {
    tag: 'section',
    description: '見出しを伴う汎用的なセクションを表す要素。',
    categories: ['flow', 'sectioning', 'palpable'],
    contentModel: { kind: 'elements', categories: ['flow'], elements: [] },
    contexts: { categories: ['flow'], elements: [] },
    void: false,
  },
  {
    tag: 'select',
    description: '選択肢から値を選ぶフォームコントロール要素。',
    categories: ['flow', 'phrasing', 'interactive', 'palpable'],
    formCategories: [
      'listed',
      'labelable',
      'submittable',
      'resettable',
      'form-associated',
    ],
    contentModel: {
      kind: 'elements',
      categories: ['select-inner'],
      elements: [],
      conditionalElements: ['button'],
      note: 'カスタマイズ可能な select のとき、先頭に button を1つ置ける',
    },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'selectedcontent',
    description: 'select内で選択中option内容を複製表示する要素。',
    categories: [],
    contentModel: { kind: 'empty', categories: [], elements: [] },
    contexts: { categories: [], elements: ['button'] },
    void: true,
  },
  {
    tag: 'slot',
    description: 'Shadow DOMで差し込み内容を配置するプレースホルダー要素。',
    categories: ['flow', 'phrasing'],
    contentModel: {
      kind: 'transparent',
      categories: [],
      elements: [],
      note: '親のcontent modelに従う。フォールバック内容を持てる。',
    },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'small',
    description: '免責事項や注釈などの注記を表す要素。',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'source',
    description: 'picture/video/audioに複数メディア候補を指定する要素。',
    categories: [],
    contentModel: { kind: 'empty', categories: [], elements: [] },
    contexts: { categories: [], elements: ['picture', 'video', 'audio'] },
    void: true,
  },
  {
    tag: 'span',
    description: '意味を持たない汎用的なインラインコンテナ要素。',
    categories: ['flow', 'phrasing', 'palpable'],
    conditionalCategories: ['option-inner'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'strong',
    description: '強い重要性や緊急性を表す要素。',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'style',
    description: '文書に埋め込むCSSスタイル情報を表す要素。',
    categories: ['metadata'],
    contentModel: {
      kind: 'text',
      categories: [],
      elements: [],
      note: 'CSS等のスタイル情報',
    },
    contexts: {
      categories: [],
      elements: ['head'],
      conditionalElements: ['noscript'],
    },
    void: false,
  },
  {
    tag: 'sub',
    description: '下付き文字を表す要素。',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'summary',
    description: 'details要素の開閉用見出しを表す要素。',
    categories: [],
    contentModel: {
      kind: 'elements',
      categories: ['phrasing', 'heading'],
      elements: [],
    },
    contexts: { categories: [], elements: ['details'] },
    void: false,
  },
  {
    tag: 'sup',
    description: '上付き文字を表すフレージング要素。',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'svg',
    description: 'SVGベクターグラフィックの埋め込み要素。',
    categories: ['flow', 'phrasing', 'embedded', 'palpable'],
    contentModel: {
      kind: 'foreign',
      categories: [],
      elements: [],
      note: 'SVGの独自コンテンツ',
    },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'table',
    description: '表形式データを表すテーブル要素。',
    categories: ['flow', 'palpable'],
    contentModel: {
      kind: 'elements',
      categories: ['script-supporting'],
      elements: ['caption', 'colgroup', 'thead', 'tbody', 'tfoot', 'tr'],
    },
    contexts: { categories: ['flow'], elements: [] },
    void: false,
  },
  {
    tag: 'tbody',
    description: 'テーブルの本体行をまとめる要素。',
    categories: [],
    contentModel: {
      kind: 'elements',
      categories: ['script-supporting'],
      elements: ['tr'],
    },
    contexts: { categories: [], elements: ['table'] },
    void: false,
  },
  {
    tag: 'td',
    description: 'テーブルのデータセル。',
    categories: [],
    contentModel: { kind: 'elements', categories: ['flow'], elements: [] },
    contexts: { categories: [], elements: ['tr'] },
    void: false,
  },
  {
    tag: 'template',
    description: 'クライアントで複製するコンテンツの雛形。',
    categories: ['metadata', 'flow', 'phrasing', 'script-supporting'],
    contentModel: {
      kind: 'none',
      categories: [],
      elements: [],
      note: '内容モデルは Nothing。記述した内容は content の DocumentFragment に格納される',
    },
    contexts: {
      categories: ['metadata', 'phrasing', 'script-supporting'],
      elements: [],
      conditionalElements: ['colgroup'],
    },
    void: false,
  },
  {
    tag: 'textarea',
    description: '複数行のテキスト入力フォーム部品。',
    categories: ['flow', 'phrasing', 'interactive', 'palpable'],
    formCategories: [
      'listed',
      'labelable',
      'submittable',
      'resettable',
      'form-associated',
    ],
    contentModel: { kind: 'text', categories: [], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'tfoot',
    description: 'テーブルのフッター行をまとめる要素。',
    categories: [],
    contentModel: {
      kind: 'elements',
      categories: ['script-supporting'],
      elements: ['tr'],
    },
    contexts: { categories: [], elements: ['table'] },
    void: false,
  },
  {
    tag: 'th',
    description: 'テーブルの見出しセル。',
    categories: [],
    contentModel: {
      kind: 'elements',
      categories: [],
      elements: [],
      conditionalCategories: ['flow'],
      note: '見出し・section・header/footer を子孫に持たない flow コンテンツ',
    },
    contexts: { categories: [], elements: ['tr'] },
    void: false,
  },
  {
    tag: 'thead',
    description: 'テーブルのヘッダー行をまとめる要素。',
    categories: [],
    contentModel: {
      kind: 'elements',
      categories: ['script-supporting'],
      elements: ['tr'],
    },
    contexts: { categories: [], elements: ['table'] },
    void: false,
  },
  {
    tag: 'time',
    description: '日時や期間を機械可読に表す要素。',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'title',
    description: '文書のタイトルを表すメタデータ要素。',
    categories: ['metadata'],
    contentModel: { kind: 'text', categories: [], elements: [] },
    contexts: { categories: [], elements: ['head'] },
    void: false,
  },
  {
    tag: 'tr',
    description: 'テーブルの行。セル(th/td)をまとめる。',
    categories: [],
    contentModel: {
      kind: 'elements',
      categories: ['script-supporting'],
      elements: ['td', 'th', 'script', 'template'],
      note: 'セル（td / th）とスクリプトサポート要素を子に持つ。',
    },
    contexts: {
      categories: [],
      elements: ['table', 'thead', 'tbody', 'tfoot'],
    },
    void: false,
  },
  {
    tag: 'track',
    description: 'メディア要素の字幕やキャプションを指定。',
    categories: [],
    contentModel: { kind: 'empty', categories: [], elements: [] },
    contexts: { categories: [], elements: ['audio', 'video'] },
    void: true,
  },
  {
    tag: 'u',
    description: '非言語的に注釈付けされたテキスト範囲。',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'ul',
    description: '順序なしリスト。',
    categories: ['flow'],
    conditionalCategories: ['palpable'],
    contentModel: {
      kind: 'elements',
      categories: ['script-supporting'],
      elements: ['li', 'script', 'template'],
    },
    contexts: { categories: ['flow'], elements: [] },
    void: false,
  },
  {
    tag: 'var',
    description: '変数や数式中の変数を表す。',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'video',
    description: '動画コンテンツを埋め込む。',
    categories: ['flow', 'phrasing', 'embedded', 'palpable'],
    conditionalCategories: ['interactive'],
    contentModel: {
      kind: 'transparent',
      categories: [],
      elements: ['source', 'track'],
      note: '親のcontent modelに従う。src 属性が無い場合は source* を子に持てる（track* は src の有無に関わらず可）。',
    },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'wbr',
    description: '改行可能位置を示す。',
    categories: ['flow', 'phrasing'],
    contentModel: { kind: 'empty', categories: [], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: true,
  },
];

// データセットに含まれる全タグ名（出現順 = ほぼアルファベット順）。
export const HTML_ELEMENT_TAGS: readonly string[] = HTML_ELEMENTS.map(
  (element) => element.tag,
);
