name: Setup pnpm
description: Setup pnpm

runs:
  using: 'composite'
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@1e1c8eafbd745f64b1ef30a7d7ed7965034c486c

    - name: Setup Node.js
      uses: actions/setup-node@d02c89dce7e1ba9ef629ce0680989b3a1cc72edb
      with:
        node-version-file: 'package.json'
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
