name: Setup pnpm
description: Setup pnpm

runs:
  using: 'composite'
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      shell: bash

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: 'package.json'
        cache: 'pnpm'
      shell: bash

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
