name: Setup pnpm
description: Setup pnpm

runs:
  using: 'composite'
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@3a0024f0665291c8c6c9957134b033a5e639e837

    - name: Setup Node.js
      uses: actions/setup-node@633bb92bc0aabcae06e8ea93b85aecddd374c402
      with:
        node-version-file: 'package.json'
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
