name: 'Chromatic'

on: push

permissions:
  contents: read

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout branch
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup
        uses: ./.github/actions/setup
      - name: Publish Main to Chromatic
        uses: chromaui/action@05812acac141ce7d317a3f787be88122bca27cf4 # v17.3.0
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          onlyChanged: true
          skip: 'renovate/**'
          workingDir: apps/main
      - name: Publish Admin to Chromatic
        uses: chromaui/action@05812acac141ce7d317a3f787be88122bca27cf4 # v17.3.0
        with:
          projectToken: ${{ secrets.CHROMATIC_ADMIN_PROJECT_TOKEN }}
          onlyChanged: true
          skip: 'renovate/**'
          workingDir: apps/admin
