name: 'Chromatic'

on: push

permissions:
  contents: read

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout branch
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup
        uses: ./.github/actions/setup
      - name: Publish Main to Chromatic
        uses: chromaui/action@5c6ec06f45a2117a25f07b1bf2b2f3009233fac8 # v16.3.0
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          onlyChanged: true
          skip: 'renovate/**'
          workingDir: apps/main
      - name: Publish Admin to Chromatic
        uses: chromaui/action@5c6ec06f45a2117a25f07b1bf2b2f3009233fac8 # v16.3.0
        with:
          projectToken: ${{ secrets.CHROMATIC_ADMIN_PROJECT_TOKEN }}
          onlyChanged: true
          skip: 'renovate/**'
          workingDir: apps/admin
