name: ci

on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout branch
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup
        uses: ./.github/actions/setup

      - name: Run ls-lint
        run: pnpm run ls-lint

      - name: Run check
        run: pnpm biome ci

      - name: Run type check
        run: pnpm run type-check

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout branch
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup
        uses: ./.github/actions/setup

      - name: Install Playwright
        run: pnpm run install-playwright

      - name: Run test
        run: pnpm run test
