name: Renovate

on:
  schedule:
    - cron: '0 15,18,21 * * 5'
    - cron: '0 0 * * 6'
  issues:
    types: [edited]
  pull_request:
    types: [edited]
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    if: >-
      github.event_name != 'issues' && github.event_name != 'pull_request' ||
      contains(github.event.*.labels.*.name, 'renovate')
    steps:
      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3.0.0
        with:
          app-id: ${{ secrets.K35O_BOT_APP_ID }}
          private-key: ${{ secrets.K35O_BOT_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          token: ${{ steps.generate-token.outputs.token }}

      - name: Run Renovate
        uses: renovatebot/github-action@68a3ea99af6ad249940b5a9fdf44fc6d7f14378b # v46.1.6
        with:
          token: ${{ steps.generate-token.outputs.token }}
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
